[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
preset = "desktop" # Optionally run Lighthouse using a desktop configuration

[template.environment]
NUXT_PUBLIC_DEFAULT_LOCALE = 'Default Locale'
NUXT_PUBLIC_GIST_ID = "Gist ID"
SERVER_PRESET = "Server Preset (netlify_edge)"
