[build]
publish = "dist"
command = "pnpm run build"

[build.environment]
NODE_VERSION = "22"

[[plugins]]
package = "@netlify/plugin-lighthouse"

[plugins.inputs.settings]
preset = "desktop" # Optionally run Lighthouse using a desktop configuration
