catalog:
  '@antfu/eslint-config': ^6.0.0
  '@iconify-json/material-symbols': ^1.2.42
  '@iconify-json/mdi': ^1.2.3
  '@jsume/schemas': ^0.0.6
  '@nuxt/eslint': 1.9.0
  '@nuxt/fonts': 0.11.4
  '@nuxt/icon': 2.1.0
  '@nuxtjs/i18n': 10.1.1
  '@pinia/nuxt': ^0.11.2
  '@types/node': ^24.9.1
  '@unocss/eslint-plugin': ^66.5.4
  '@unocss/nuxt': 66.5.4
  '@unocss/reset': ^66.5.4
  '@vueuse/core': ^14.0.0
  '@vueuse/integrations': ^14.0.0
  '@vueuse/nuxt': ^14.0.0
  drauu: ^0.4.3
  eslint: ^9.38.0
  lint-staged: ^16.2.6
  nuxt: ^4.1.3
  pinia: ^3.0.3
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  unocss: ^66.5.4
  vue: ^3.5.22
  vue-router: ^4.6.3
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
