catalog:
  '@antfu/eslint-config': ^5.4.1
  '@iconify-json/material-symbols': ^1.2.40
  '@iconify-json/mdi': ^1.2.3
  '@jsume/schemas': ^0.0.6
  '@nuxt/eslint': 1.9.0
  '@nuxt/fonts': 0.11.4
  '@nuxt/icon': 2.0.0
  '@nuxtjs/i18n': 10.1.0
  '@pinia/nuxt': ^0.11.2
  '@types/node': ^24.7.0
  '@unocss/eslint-plugin': ^66.5.2
  '@unocss/nuxt': 66.5.2
  '@unocss/reset': ^66.5.2
  '@vueuse/core': ^13.9.0
  '@vueuse/nuxt': ^13.9.0
  eslint: ^9.37.0
  lint-staged: ^16.2.3
  nuxt: ^4.1.3
  pinia: ^3.0.3
  simple-git-hooks: ^2.13.1
  typescript: ^5.9.3
  unocss: ^66.5.2
  vue: ^3.5.22
  vue-router: ^4.5.1
  zod: ^4.1.12

onlyBuiltDependencies:
  - '@parcel/watcher'
  - esbuild
  - simple-git-hooks
  - unrs-resolver
